<a href="https://colab.research.google.com/github/sam85avila/linguagem-programacao-python/blob/main/aula02_sessao_01_linguagem_programacao.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# List comprehension

In [ ]:
linguagens = ["Python", "Java", "JavaScript", "C", "C#", "C++", "Swift", "Go", "Kotlin"]
              
linguagens = [item.upper() for item in linguagens]

print(linguagens)

['PYTHON', 'JAVA', 'JAVASCRIPT', 'C', 'C#', 'C++', 'SWIFT', 'GO', 'KOTLIN']


In [1]:
linguagens = ["Python", "Java", "JavaScript", "C", "C#", "C++", "Swift", "Go", "Kotlin"]

linguagens_c = [item for item in linguagens if 'C' in item]

print(linguagens_c)

['C', 'C#', 'C++']


# Função Map

In [ ]:
# a função split() cria uma lista a partir de uma string
linguagens = '''Python Java JavaScript C C# C++ Swift Go Kotlin'''.split() 

linguagens2 = map(lambda item: item.upper(), linguagens)

# Necessário transformar o objeto em uma lista 
# Pois a função map() retorna um objeto iterável
linguagens2 = list(linguagens2) 

print(linguagens2)

['PYTHON', 'JAVA', 'JAVASCRIPT', 'C', 'C#', 'C++', 'SWIFT', 'GO', 'KOTLIN']


In [ ]:
numeros = [0, 1, 2, 3, 4, 5]

quadrado = list(map(lambda x: x*x, numeros))

print(quadrado)

[0, 1, 4, 9, 16, 25]


# Função Filter()

In [ ]:
numeros = list(range(1, 21))

num_par = list(filter(lambda x: x % 2 == 0, numeros))

num_impar = list(filter(lambda x: x % 2 != 0, numeros))

print(f"Números pares: {num_par}")
print(f"Números impares: {num_impar}")


Números pares: [2, 4, 6, 8, 10, 12, 14, 16, 18, 20]
Números impares: [1, 3, 5, 7, 9, 11, 13, 15, 17, 19]


# Tuple

In [ ]:
vogais = ('a', 'e', 'i', 'o', 'u')

for item in enumerate(vogais):
  print(item)

print("Tuple de tuplas:", tuple(enumerate(vogais)))
print("Lista de tuplas:", list(enumerate(vogais)))

(0, 'a')
(1, 'e')
(2, 'i')
(3, 'o')
(4, 'u')
Tuple de tuplas: ((0, 'a'), (1, 'e'), (2, 'i'), (3, 'o'), (4, 'u'))
Lista de tuplas: [(0, 'a'), (1, 'e'), (2, 'i'), (3, 'o'), (4, 'u')]


# Set

In [ ]:
componentes_verificados = set(['caixas de som', 'cooler', 'dissipador de calor', 
                               'cpu', 'hd', 'estabilizador', 'gabinete', 'hub', 
                               'impressora', 'joystick', 'memória ram', 'microfone', 
                               'modem', 'monitor', 'mouse', 'no-break', 'placa de captura', 
                               'placa de som', 'placa de vídeo', 'placa mãe', 'scanner', 
                               'teclado', 'webcam'])
componentes_com_defeito = set(['hd', 'monitor', 'placa de som', 'scanner'])

qtd_comp_verificados = len(componentes_verificados)
qtd_comp_defeito = len(componentes_com_defeito)

componentes_ok = componentes_verificados.difference(componentes_com_defeito)

componentes = []

for i, item in enumerate(componentes_ok):
  componentes.append(item)

print(componentes)
#print(qtd_comp_verificados)
#print(qtd_comp_defeito)


In [ ]:
impar = set([1, 3, 5, 7, 9])
num = set(range(1,11))

tudo = impar.intersection(num)

print(tudo)

{1, 3, 5, 7, 9}


# Mapping

In [ ]:


cadastro = {
            'nome' : ['João', 'Ana', 'Pedro', 'Marcela'],
            'cidade' : ['São Paulo', 'São Paulo', 'Rio de Janeiro', 'Curitiba'],
            'idade' : [25, 33, 37, 18]
            }

print("len(cadastro) = ", len(cadastro))

print("\n cadastro.keys() = \n", cadastro.keys())
print("\n cadastro.values() = \n", cadastro.values())
print("\n cadastro.items() = \n", cadastro.items())

print("\n cadastro['nome'] = ", cadastro['nome'])
print("\n cadastro['nome'][2] = ", cadastro['nome'][2])
print("\n cadastro['idade'][2:] = ", cadastro['idade'][2:])



len(cadastro) =  3

 cadastro.keys() = 
 dict_keys(['nome', 'cidade', 'idade'])

 cadastro.values() = 
 dict_values([['João', 'Ana', 'Pedro', 'Marcela'], ['São Paulo', 'São Paulo', 'Rio de Janeiro', 'Curitiba'], [25, 33, 37, 18]])

 cadastro.items() = 
 dict_items([('nome', ['João', 'Ana', 'Pedro', 'Marcela']), ('cidade', ['São Paulo', 'São Paulo', 'Rio de Janeiro', 'Curitiba']), ('idade', [25, 33, 37, 18])])

 cadastro['nome'] =  ['João', 'Ana', 'Pedro', 'Marcela']

 cadastro['nome'][2] =  Pedro

 cadastro['idade'][2:] =  [37, 18]


Array Numpy

In [ ]:
import numpy as np

matriz_1_3 = np.array([1, 2, 3])
matriz_2_2 = np.array([[1, 3], [5, 7]])
matriz_3_2 = np.array([[1, 2], [3, 4], [5, 6]]) 
matriz_2_3 = np.array([[1, 2, 3], [4, 5, 6]]) 

print("\nMatriz_1_3 \n", matriz_1_3)
print("\nMatriz_2_2 \n", matriz_2_2)
print("\nMatriz_3_2 \n", matriz_3_2)
print("\nMatriz_2_3 \n", matriz_2_3)


Matriz_1_3 
 [1 2 3]

Matriz_2_2 
 [[1 3]
 [5 7]]

Matriz_3_2 
 [[1 2]
 [3 4]
 [5 6]]

Matriz_2_3 
 [[1 2 3]
 [4 5 6]]


In [ ]:
m1 = np.zeros((2, 3))
m2 = np.ones((2, 5))
m3 = np.eye(3)
m4 = np.random.randint(low=0, high=50, size=8).reshape(2, 4)

print(m1)
print("\n", m2)
print("\n", m3)
print("\n", m4)


[[0. 0. 0.]
 [0. 0. 0.]]

 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

 [[29 14 42 47]
 [ 8 12 41 22]]


In [ ]:
m1 = np.zeros((2, 3))
m2 = np.ones((2, 5))
m3 = np.eye(3)
m4 = np.random.randint(low=0, high=100, size=8).reshape(2, 4)

print(f"Array m4: \n{m4}")
print(f"A soma dos valores de m4: {m4.sum()}")
print(f"O valor mínimo de m4: {m4.min()}")
print(f"O valor máximo de m4: {m4.max()}")
print(f"A média dos valores de m4: {m4.mean()}")


Array m4: 
[[60 77 66 70]
 [45 19 22 99]]
A soma dos valores de m4: 458
O valor mínimo de m4: 19
O valor máximo de m4: 99
A média dos valores de m4: 57.25


# Foco no mercado

In [3]:
def extrair_lista_email(dict_1, dict_2):
  lista_1 = list(zip(dict_1['nome'], dict_1['email'], dict_1['enviado']))
  print(f"Amostra da lista 1 =\n {lista_1[0]}")

  lista_2 = list(zip(dict_2['nome'], dict_2['email'], dict_2['enviado']))

  dados = lista_1 + lista_2
  print(f"\nAmostra dos dados = \n{dados[:2]}\n")

  # pegamos o item[1] na tupla que é o email; o item[2] é status de enviado,
  # no caso, pegamos apenas se for False, por conta da negação(not) apontada.
  emails = [item[1] for item in dados if not item[2]]

  return emails

dados_1 = {
  'nome': ['Sonia Weber', 'Daryl Lowe', 'Vernon Carroll', 'Basil Gilliam', 'Mechelle Cobb', 'Edan Booker', 'Igor Wyatt', 'Ethan Franklin', 'Reed Williamson', 'Price Singleton'],
  'email': ['Lorem.ipsum@cursusvestibulumMauris.com', 'auctor@magnis.org', 'at@magnaUttincidunt.org', 'mauris.sagittis@sem.com', 'nec.euismod.in@mattis.co.uk', 'egestas@massaMaurisvestibulum.edu', 'semper.auctor.Mauris@Crasdolordolor.edu', 'risus.Quisque@condimentum.com', 'Donec@nislMaecenasmalesuada.net', 'Aenean.gravida@atrisus.edu'],
  'enviado': [False, False, False, False, False, False, False, True, False, False]
}

dados_2 = {
  'nome': ['Travis Shepherd', 'Hoyt Glass', 'Jennifer Aguirre', 'Cassady Ayers', 'Colin Myers', 'Herrod Curtis', 'Cecilia Park', 'Hop Byrd', 'Beatrice Silva', 'Alden Morales'],
  'email': ['at@sed.org', 'ac.arcu.Nunc@auctor.edu', 'nunc.Quisque.ornare@nibhAliquam.co.uk', 'non.arcu@mauriseu.com', 'fringilla.cursus.purus@erategetipsum.ca', 'Fusce.fermentum@tellus.co.uk', 'dolor.tempus.non@ipsum.net', 'blandit.congue.In@libero.com', 'nec.tempus.mauris@Suspendisse.com', 'felis@urnaconvalliserat.org'],
  'enviado': [False, False, False, True, True, True, False, True, True, False]
}

emails = extrair_lista_email(dados_1, dados_2)
print(f"Emails a serem enviados:\n{emails}")


Amostra da lista 1 =
 ('Sonia Weber', 'Lorem.ipsum@cursusvestibulumMauris.com', False)

Amostra dos dados = 
[('Sonia Weber', 'Lorem.ipsum@cursusvestibulumMauris.com', False), ('Daryl Lowe', 'auctor@magnis.org', False)]

Emails a serem enviados:
['Lorem.ipsum@cursusvestibulumMauris.com', 'auctor@magnis.org', 'at@magnaUttincidunt.org', 'mauris.sagittis@sem.com', 'nec.euismod.in@mattis.co.uk', 'egestas@massaMaurisvestibulum.edu', 'semper.auctor.Mauris@Crasdolordolor.edu', 'Donec@nislMaecenasmalesuada.net', 'Aenean.gravida@atrisus.edu', 'at@sed.org', 'ac.arcu.Nunc@auctor.edu', 'nunc.Quisque.ornare@nibhAliquam.co.uk', 'dolor.tempus.non@ipsum.net', 'felis@urnaconvalliserat.org']
